version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'  
  base-directory: 'dist*'
  discard-paths: yes